# Generated by Django 3.0.7 on 2020-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200831_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_post',
            field=models.TextField(default='', max_length=600),
        ),
    ]
